In [1]:
#importing pandas package
import pandas as pd
import numpy as np

path_to_projectData = 'Data/' #input path where the data of the project resides
train_data_df = pd.read_csv(path_to_projectData + 'training_data_2_csv_UTF.csv') #reading the bots_data.csv file
train_data_df.head(10)

#SELECTING TOP 10 ROWS FROM THE COMBINED DATASET|

,id,id_str,screen_name,location,description,url,followers_count,friends_count,listedcount,created_at,favourites_count,verified,statuses_count,lang,status,default_profile,default_profile_image,has_extended_profile,name,bot
0,8.160000e+17,"""815745789754417152""","""HoustonPokeMap""","""Houston, TX""","""Rare and strong PokŽmon in Houston, TX. See m...","""https://t.co/dnWuDbFRkt""",1291,0,10,"""Mon Jan 02 02:25:26 +0000 2017""",0,False,78554,"""en""","{\r ""created_at"": ""Sun Mar 12 15:44:04 +0...",True,False,False,"""Houston PokŽ Alert""",1
1,4.843621e+09,4843621225,kernyeahx,"Templeville town, MD, USA",From late 2014 Socium Marketplace will make sh...,NaN,1,349,0,2/1/2016 7:37,38,False,31,en,null,True,False,False,Keri Nelson,1
2,4.303727e+09,4303727112,mattlieberisbot,NaN,"Inspired by the smart, funny folks at @replyal...",https://t.co/P1e1o0m4KC,1086,0,14,Fri Nov 20 18:53:22 +0000 2015,0,False,713,en,"{'retweeted': False, 'is_quote_status': False,...",True,False,False,Matt Lieber Is Bot,1
3,3.063139e+09,3063139353,sc_papers,NaN,NaN,NaN,33,0,8,2/25/2015 20:11,0,False,676,en,Construction of human anti-tetanus single-chai...,True,True,False,single cell papers,1
4,2.955142e+09,2955142070,lucarivera16,"Dublin, United States",Inspiring cooks everywhere since 1956.,NaN,11,745,0,1/1/2015 17:44,146,False,185,en,null,False,False,False,lucarivera16,1
5,8.410000e+17,8.41E+17,dantheimprover,"Austin, TX",Just a guy trying to do good by telling everyo...,NaN,1,186,0,13/03/2017 22:53,0,False,11,en,Status(_api=<tweepy.api.API object at 0x101927...,True,False,True,dantheimprover,1
6,2.482835e+09,2482834658,_all_of_us_,in a machine.,bot by @rubicon,NaN,193,0,19,Wed May 07 22:29:25 +0000 2014,0,False,6068,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,everything always,1
7,3.333574e+09,3333573622,KatamariItems,NaN,[Bot rolled up by @BeachEpisode] Cataloguing e...,NaN,8227,2,89,Thu Jun 18 22:07:31 +0000 2015,26,False,2597,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,Katamari Collection,1
8,2.996105e+09,2996105102,AutophagyPapers,NaN,Twitterbot for #Autophagy papers. Curated by @...,NaN,275,0,17,1/25/2015 17:34,23,False,9922,en,Feeding Schedule And Proteolysis Regulate Auto...,False,False,False,Autophagy Papers,1
9,3.271096e+09,3271095818,HSC_papers,NaN,NaN,NaN,51,3,9,7/7/2015 15:23,0,False,2515,en,Functional Selectivity in Cytokine Signaling R...,True,False,False,Hematopoiesis,1

In [5]:
#import train_test_split,Imputer from sklearn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer

# selecting attributes which have numeric values and categorical values
train_data= train_data_df[['location','description',
       'followers_count', 'friends_count', 'listedcount','created_at',
       'favourites_count', 'verified', 'statuses_count','default_profile','default_profile_image','has_extended_profile','name']]


train_data['followers_count']=train_data['followers_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
train_data['friends_count']=train_data['friends_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
# train_data['location']=train_data['location'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
train_data['list_count']=train_data['listedcount'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
train_data['fav_count']=train_data['favourites_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)

train_data.drop('listedcount', axis=1, inplace=True)
train_data.drop('favourites_count', axis=1, inplace=True)
#y = lambda symbol: 'X' if symbol==True else 'O' if symbol==False else ' '

train_data['verified']=train_data['verified'].apply(lambda x: 0 if x==False else 1 if x==True else -1)
train_data['default_profile']=train_data['default_profile'].apply(lambda x: 0 if x==False else 1 if x==True else -1)
train_data['default_profile_image']=train_data['default_profile_image'].apply(lambda x: 0 if x==False else 1 if x==True else -1)
train_data['has_extended_profile']=train_data['has_extended_profile'].apply(lambda x: 0 if x==False else 1 if x==True else -1)




# train_data['is_bot_screenname']=0
# train_data['is_bot_screenname'] = train_data['screen_name'].apply(lambda x:1 if 'bot' in x  else 1 if 'Bot' in x  else 1 
#                                                                    if 'BOT' in x else 0)
# train_data.drop('screen_name', axis=1, inplace=True)



#Looking for the word bot in description   
train_data['is_bot_description']=0
description = train_data['description']
flag = []
for x in description:
    x = str(x)
    if 'bot' in x or 'BOT' in x or 'Bot' in x:
        flag.append(1)
    else:
        flag.append(0)
train_data['is_bot_description']=flag
train_data.drop('description', axis=1, inplace=True)

#namelength computation
train_data['name_len']=0

profilenames = train_data['name']
namelen = []
for i in profilenames:
    namelen.append(len(i))
train_data['name_len']=namelen
train_data.drop('name', axis=1, inplace=True)


#computing the number of days since profile creation
timestamp = train_data_df['created_at']
train_data['age_of_profile']=0
profile_age=[]
from datetime import datetime

DATE_FORMATS = ['%a %b %d %H:%M:%S +0000 %Y','"%a %b %d %H:%M:%S +0000 %Y"','%Y-%m-%d %H:%M:%S','%d/%m/%Y %H:%M' , '%m/%d/%Y %H:%M']

for i in timestamp:
    try:
        for dateformat in DATE_FORMATS:
            try:
                my_date = datetime.strptime(i,dateformat)
                break
            except ValueError:
                pass
        today = datetime.today()
        difference = today - my_date
        profile_age.append(difference.days)
    except ValueError:
        pass

train_data['age_of_profile']=profile_age
train_data.drop('created_at', axis=1, inplace=True)


#location and url 
train_data['location']=train_data['location'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)
#train_data['url']=train_data['url'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)
train_data


X_train=train_data
Y_train=train_data_df['bot']

X_train

# train_data

# df = pd.DataFrame(['05/06/2015 00:00', '22/06/2015 00:00', None], columns=['myDate'])
# df['diff']= pd.to_datetime(train_data['myDate'], coerce=True) - pd.datetime.now().date()
# df

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,location,followers_count,friends_count,verified,statuses_count,default_profile,default_profile_image,has_extended_profile,list_count,fav_count,is_bot_description,name_len,age_of_profile
0,1,1291,0,0,78554,1,0,0,10,0,0,21,123
1,1,1,349,0,31,1,0,0,0,38,0,11,489
2,1,1086,0,0,713,1,0,0,14,0,1,18,532
3,1,33,0,0,676,1,1,0,8,0,0,18,800
4,1,11,745,0,185,0,0,0,0,146,0,12,855
5,1,1,186,0,11,1,0,1,0,0,0,14,52
6,1,193,0,0,6068,0,0,0,19,0,1,17,1093
7,1,8227,2,0,2597,1,0,0,89,26,1,19,686
8,1,275,0,0,9922,0,0,0,17,23,1,16,831
9,1,51,3,0,2515,1,0,0,9,0,0,13,668
10,1,51,1,0,111,0,0,0,12,0,0,17,1001
11,1,2,1,0,230,1,1,0,4,0,1,9,956
12,1,0,29,0,0,1,1,-1,0,0,0,11,54
13,1,1,206,0,0,1,1,-1,0,0,0,9,1595
14,1,0,38,0,0,1,1,-1,0,0,0,16,54
15,1,109,0,0,16067,1,0,0,16,0,0,17,805
16,1,250,0,0,31721,1,0,0,25,0,0,19,1055
17,1,15,1941,0,406,0,0,0,1,319,0,15,855
18,1,190,1899,0,0,1,1,0,0,27,0,3,-60
19,1,181,0,0,21506,1,1,0,24,0,1,17,948
20,1,10175,11465,0,65022,1,0,0,199,328,0,4,1313
21,1,23,4,0,6230,0,0,0,8,4,0,17,1098
22,1,106126,0,0,30156,1,0,0,999,2,0,11,1316
23,1,2302,3,0,7640,0,0,0,161,4,1,12,555
24,1,443,2,0,9584,0,0,0,17,6,1,12,576
25,1,27,1,0,145,1,0,0,10,0,0,20,1061
26,1,191,2,0,5684,0,0,0,19,0,0,8,1077
27,1,1,35,0,82,1,0,0,1,54,0,14,88
28,1,651,0,0,19867,0,0,0,36,0,1,19,1210
29,1,37,45,0,191,0,0,0,7,0,0,16,975
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,1,1017758,6985,1,13786,0,0,0,9473,12901,0,12,3158
2768,1,9,97,0,1,1,0,1,0,0,0,11,1169
2769,1,2000567,457,1,55202,0,0,0,9674,901,0,10,2879
2770,1,11,53,0,13,1,0,0,0,1,0,10,2385
2771,1,1599,922,0,11240,0,0,1,67,212,0,17,3015
2772,1,82,91,0,704,0,0,0,0,634,0,5,1416
2773,1,178,325,0,405,0,0,0,6,30,0,11,1705
2774,1,46,233,0,285,1,0,-1,0,935,0,13,2059
2775,1,67,168,0,1851,0,0,0,0,0,0,14,2447
2776,1,147441,20889,1,7648,0,0,0,0,43,0,13,3094
2777,1,420699,108,1,5568,0,0,0,5248,11,0,14,2974
2778,1,63866,21,1,70,0,0,0,2037,40,0,11,2788
2779,1,1715,1342,0,1395,0,0,1,84,3688,0,20,2857
2780,1,5,67,0,2,0,0,0,0,0,0,13,2277
2781,1,122,88,0,1031,0,0,1,0,325,0,13,1466
2782,1,4025,487,1,6672,0,0,0,117,18,0,10,2835
2783,1,52,39,0,206,0,0,-1,0,689,0,13,321
2784,1,30,72,0,926,0,0,0,4,1,0,13,1742
2785,1,41776,1158,1,1096,0,0,0,854,1264,0,10,2991
2786,1,52,323,0,767,0,0,1,2,696,0,17,2561
2787,1,972032,3072,1,22362,0,0,0,1587,1423,0,14,2826
2788,1,26,150,0,2,1,1,0,1,8,0,10,2670
2789,1,215,462,0,2384,0,0,0,16,812,0,11,3255
2790,1,64219,667,1,85,0,0,0,698,2901,0,5,2851
2791,1,310,0,0,3909,1,0,0,21,3,0,14,1240
2792,1,18998,2005,0,3498,0,0,1,425,2503,0,14,2043
2793,1,32,54,0,97,1,0,0,0,1,0,18,2267
2794,1,45044433,7451,1,9606,0,0,0,68157,24,0,12,3213
2795,1,16,64,0,62,0,0,1,1,15,0,14,1639
2796,1,22490,308,1,1897,1,0,1,1342,43,0,10,3014

In [ ]:

# profile_age

# for i in timestamp:
#     try:
#         for date_format in DATE_FORMATS:
#             try:
#                 my_date = datetime.strptime(i, date_format)
#                 break
#             except Exception as e:
#                 print e.message
#                 pass
#         print my_date
#         today = datetime.today()
#         difference = today - my_date
#         profile_age.append(difference.days)
#         break
#     except ValueError:
#         pass

In [ ]:
# train_data['name_loc']=0
# text_data=list(train_data.apply(lambda x:'%s %s' %(train_data['screen_name'],train_data['location']),axis=1)) 
# from sklearn.feature_extraction.text import TfidfVectorizer

# tfv=TfidfVectorizer(min_df=3,max_features=None,strip_accents='unicode')
# text_data_train=tfv.fit_transform(text_data)
# text_data_train

# train_data.drop('screen_name', axis=1, inplace=True)
# train_data.drop('location', axis=1, inplace=True)

# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.feature_extraction.text import TfidfTransformer
# from scipy.sparse import csr_matrix 
# from  sklearn.neighbors import NearestNeighbors
# from sklearn.neighbors import KDTree

# cv = CountVectorizer()
# text_data_train = cv.fit_transform(text_data)

# tfv_transformer = TfidfTransformer()
# X_text_data_train = tfv_transformer.fit_transform(text_data_train)
# X_text_data_train


# X_train['name_loc']=numeric
# X_train['name_loc']
# X_train=train_data

# X_train['name_loc']


# train_data[['screen_name','location']] = train_data[['screen_name','location']].apply(pd.to_numeric)

In [6]:
test_data_df= pd.read_csv(path_to_projectData + 'test_data_4_students.csv')
##test_data_df.replace('None',0,inplace=True)
test_data_df.head(10)

test_data_df=test_data_df.head(575)

test_data= test_data_df[['location','description',
       'followers_count', 'friends_count', 'listed_count','created_at',
       'favorites_count', 'verified', 'statuses_count','default_profile','default_profile_image','has_extended_profile','name']]



#df.Age.apply(lambda x: x if not pd.isnull(x) else 'Is Null value')
test_data['followers_count']=test_data['followers_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data['friends_count']=test_data['friends_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data['list_count']=test_data['listed_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data['fav_count']=test_data['favorites_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data.drop('listed_count', axis=1, inplace=True)
test_data.drop('favorites_count', axis=1, inplace=True)
#y = lambda symbol: 'X' if symbol==True else 'O' if symbol==False else ' '

test_data['verified']=test_data['verified'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)
test_data['default_profile']=test_data['default_profile'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)
test_data['default_profile_image']=test_data['default_profile_image'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)
test_data['has_extended_profile']=test_data['has_extended_profile'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)

# test_data['is_bot_description']=0

# test_data['is_bot_screenname']=0
# test_data['is_bot_screenname'] = test_data['screen_name'].apply(lambda x:1 if 'bot' in x  else 1 if 'Bot' in x  else 1 
#                                                                    if 'BOT' in x else 0)
# test_data.drop('screen_name', axis=1, inplace=True)


test_data['followers_count'].fillna(0,inplace=True)
test_data['friends_count'].fillna(0,inplace=True)
# test_data['listed_count'].fillna(0,inplace=True)
# test_data['favourites_count'].fillna(0,inplace=True)
test_data['verified'].fillna(-1,inplace=True)
test_data['default_profile'].fillna(-1,inplace=True)
test_data['default_profile_image'].fillna(-1,inplace=True)
test_data['has_extended_profile'].fillna(-1,inplace=True)
test_data['statuses_count'].fillna(0,inplace=True)
# test_data['location']=test_data['location'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)

test_data['is_bot_description']=0

#Looking for the word bot in description            
description = test_data['description']
flag = []
for x in description:
    x = str(x)
    if 'bot' in x or 'BOT' in x or 'Bot' in x:
        flag.append(1)
    else:
        flag.append(0)
test_data['is_bot_description']=flag
test_data.drop('description', axis=1, inplace=True)

#Length of name
test_data['name_len']=0

profilenames = test_data['name']
namelen = []
for i in profilenames:
    namelen.append(len(i))
test_data['name_len']=namelen
test_data.drop('name', axis=1, inplace=True)

test_data['location']=test_data['location'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)
# test_data['url']=test_data['url'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)


#computing the number of days since profile creation
timestamp = test_data['created_at']
test_data['age_of_profile']=0
profile_age=[]
from datetime import datetime

DATE_FORMATS = ['%a %b %d %H:%M:%S +0000 %Y','"%a %b %d %H:%M:%S +0000 %Y"','%Y-%m-%d %H:%M:%S','%d/%m/%Y %H:%M' , '%m/%d/%Y %H:%M']

for i in timestamp:
    try:
        for dateformat in DATE_FORMATS:
            try:
                my_date = datetime.strptime(i,dateformat)
                break
            except ValueError:
                pass
        today = datetime.today()
        difference = today - my_date
        profile_age.append(difference.days)
    except ValueError:
        pass

test_data['age_of_profile']=profile_age
test_data.drop('created_at', axis=1, inplace=True)



X_test=test_data
X_test


# #test_data['followers_count'].fillna(0,inplace=True)
# #test_data['followers_count'] = test_data['followers_count'].astype(np.int64)

# #test_data.apply(pd.to_numeric,errors='coerce')

# #Y_train=Imputer().fit_transform(test_data)

# ##print(type(test_data['followers_count']))

# ##dtypeCount = [test_data.iloc[:,i].apply(type).value_counts() for i in range(test_data.shape[1])]
# ##dtypeCount

# ##print(type(train_data['verified']))

# ##print(pd.get_dummies(test_data.verified))
# #test_data.fillna(value=np.nan, inplace=True)

# ##df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=['A', 'B', 'C', 'D'])

# ##test_data=pd.DataFrame(np.random.randn(8, 4),index=test_data_df,columns=['followers_count','friends_count','listedcount','favourites_count'])

##test_data= test_data_df.ix[:,['followers_count','friends_count','listedcount','favourites_count','verified','statuses_count',
  ##            'default_profile','default_profile_image','has_extended_profile']]




##Y_train= test_data # filling the NaN and infinite values

##Y_train.head(10)
##test_data.head(10)

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,location,followers_count,friends_count,verified,statuses_count,default_profile,default_profile_image,has_extended_profile,list_count,fav_count,is_bot_description,name_len,age_of_profile
0,1,4466,1295,1,3036.0,0,0,0,111,1579,0,15,1213
1,1,295,1016,0,618.0,0,0,0,10,300,0,16,1176
2,1,1001678,3017,1,3329.0,1,0,1,14,13040,0,14,1721
3,1,445,487,0,46.0,0,0,1,17,1112,0,12,474
4,1,187,68,-1,690359.0,-1,-1,-1,13,0,1,42,1493
5,0,80,87,-1,20167.0,1,-1,-1,0,0,1,36,1059
6,1,2020,1978,-1,968182.0,1,-1,-1,56,0,1,33,2102
7,0,70,80,-1,76735.0,1,-1,-1,2,0,1,18,1677
8,1,181,144,-1,1960.0,1,-1,-1,2,0,1,36,76
9,1,20419393,9,1,468.0,-1,-1,-1,6,0,0,10,2733
10,1,20423,8,0,17387.0,0,0,0,130,0,1,15,405
11,1,1436,2017,1,967.0,0,0,1,55,1099,0,15,1401
12,1,26376073,91,1,2666.0,-1,-1,-1,60767,0,0,19,2727
13,1,27950120,157,1,287.0,-1,-1,-1,32993,0,0,5,2440
14,1,5210,2555,1,5501.0,0,0,0,232,1169,0,13,2511
15,1,16328463,1071,1,14596.0,-1,-1,-1,10848,0,0,8,2902
16,1,964,331,0,6389.0,0,0,1,15,2832,0,14,2902
17,1,5254,2407,0,3392.0,1,0,1,102,3082,0,15,3040
18,1,446,431,-1,119680.0,-1,-1,-1,4,0,1,71,1199
19,1,1404,0,0,141.0,1,0,0,2,12,1,7,325
20,0,16933838,21,1,3673.0,-1,-1,-1,14682,0,0,12,2942
21,1,8619,3229,1,38918.0,0,0,1,190,50921,0,4,2612
22,1,15610695,36,1,82958.0,-1,-1,-1,15248,0,0,47,2978
23,0,15836207,1046,1,27660.0,-1,-1,-1,32067,0,0,14,2899
24,1,14749,1843,1,20076.0,0,0,0,584,2389,0,15,2430
25,1,191,228,0,24.0,0,0,1,5,164,0,16,879
26,1,25557131,672,1,7051.0,-1,-1,-1,51993,0,0,11,2932
27,1,13206,964,1,14115.0,0,0,0,496,3426,0,11,2541
28,1,1641,812,0,3385.0,0,0,0,91,1493,0,13,2747
29,1,4545529,2042,1,9370.0,0,0,0,12664,13260,0,11,2797
...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,1,371,4,0,1892.0,0,0,0,0,3,0,20,357
546,1,263,397,-1,62000.0,1,-1,-1,1,0,1,35,1781
547,1,50,1,0,4200.0,1,0,0,0,1,1,18,507
548,1,549,21,0,245021.0,1,0,0,298,6,1,19,888
549,1,4067,360,1,4061.0,0,0,0,152,3402,0,11,2773
550,1,486,116,-1,306390.0,-1,-1,-1,12,0,1,37,517
551,1,331,375,0,4313.0,0,0,0,18,49,1,15,633
552,0,16779295,0,1,3698.0,-1,-1,-1,9213,0,0,13,1810
553,1,892,355,0,1028.0,1,0,0,16,500,0,13,2037
554,1,25,4,0,1323.0,1,0,0,2,0,1,11,286
555,1,993,47,0,18369.0,1,0,0,1047,13,0,13,1283
556,1,210,200,0,68691.0,1,0,0,13,1442,1,9,1154
557,1,231,127,0,87.0,1,0,0,1,64,0,13,131
558,1,980,107,0,14979.0,1,0,0,59,4,1,16,2089
559,1,19,7,0,26181.0,1,0,0,1,20,1,15,792
560,1,29145797,800,1,42988.0,-1,-1,-1,27906,0,0,11,3009
561,1,297,191,0,296.0,0,0,0,12,32,0,13,3067
562,0,16296072,23,1,973.0,-1,-1,-1,20704,0,0,18,2240
563,1,15,0,-1,70833.0,1,-1,-1,0,0,1,60,1056
564,1,3065,3517,-1,74560.0,-1,-1,-1,94,0,1,27,2466
565,0,120,71,-1,51891.0,1,1,-1,3,0,1,38,1684
566,0,113,226,-1,24115.0,1,-1,-1,3,0,1,106,1057
567,0,66,84,-1,234290.0,1,1,-1,5,0,0,23,2110
568,1,47,16,-1,178704.0,1,-1,-1,3,0,1,18,1832
569,1,26841,3359,0,90417.0,0,0,0,491,130876,0,14,2239
570,1,1551,138,0,37318.0,1,0,1,3119,1,1,7,302
571,1,67697733,998,1,19364.0,-1,-1,-1,82023,0,0,7,3460
572,1,1257,363,-1,388672.0,1,-1,-1,75,0,1,26,2355
573,1,21585872,2279,1,3318.0,-1,-1,-1,128136,0,0,4,2460
574,1,64,80,0,43438.0,1,0,0,3,0,1,17,771

In [ ]:
# test_data['name_loc']=0
# text_data=list(test_data.apply(lambda x:'%s %s ' %(test_data['screen_name'],test_data['location']),axis=1)) 
# from sklearn.feature_extraction.text import TfidfVectorizer

# tfv=TfidfVectorizer(min_df=3,max_features=None,strip_accents='unicode',analyzer='word',token_pattern=r'\w{1,}',ngram_range=(1,2),use_idf=1,smooth_idf=1,sublinear_tf=1,stop_words='english')
# text_data_test=tfv.fit_transform(text_data)

# test_data['name_loc']=text_data_test
# test_data.drop('location', axis=1, inplace=True)


# X_test['name_loc']

# from sklearn.decomposition import TruncatedSVD

# svd=TruncatedSVD(n_components=50)
# svd.fit(text_data_test)
# text_data_test=svd.transform(text_data_test)

In [7]:
#Importing the DecisionTreeClassifier and predicting whether the profile is a bot or not using it
from sklearn.tree import DecisionTreeClassifier
dtree= DecisionTreeClassifier()
dtree.fit(X_train,Y_train)
dtree_predictions=dtree.predict(X_test)

#Importing the classification_report,confusion_matrix from sklearn.metrics package
from sklearn.metrics import classification_report,confusion_matrix

# #Printing the Confusion Matrix and Classification Report for DecisionTreeClassifier
# #print(confusion_matrix(Y_test,dtree_predictions))
# #print('\n')
# #print(classification_report(Y_test,dtree_predictions))

# #print("accuracy score: {} ".format(accuracy_score(Y_test, dtree_predictions)))  
# #print("AUC: {}".format(roc_auc_score(Y_test,dtree_predictions)))

In [8]:
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Join the features from train and test together before imputing missing values,
# in case their distribution is slightly different
X_train = X_train.astype('float32')
X_test=X_test.astype('float32')

# Prepare the inputs for the model
xgb= xgb.XGBClassifier(max_depth=9, n_estimators=700, learning_rate=0.04)
clf = xgb.fit(X_train,Y_train)

predictions = clf.predict(X_test)
predictions

test_data['bot'] = np.array(predictions)

result = pd.DataFrame(test_data_df['id'])

result  = result.astype(np.int64)
result['bot'] = test_data['bot']
result
print (result['id'].dtype)
print (result['bot'].dtype)
print (result)

result.to_csv('output_xgb_new.csv',  index=False)

/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

int64
int64
                     id  bot
0            2281292622    0
1            2344040251    0
2             765871267    0
3            4772373433    0
4            1324548560    1
5            2561341789    1
6             347810134    1
7             856303860    1
8    832875000000000000    1
9              88856792    0
10   713557000000000000    1
11           1566746503    0
12             90420314    0
13            184910040    0
14            157690631    0
15             42420346    0
16             42382447    0
17             43993280    0
18           2305236733    1
19   742794000000000000    1
20             31348594    0
21            122085859    0
22             23573083    0
23             43152482    0
24            188857501    0
25           2911272579    0
26             35094637    0
27            146252766    0
28             85430866    0
29             55117855    0
..                  ...  ...
545  731201000000000000    1
546           612754791    1
547          4493562022    1
548          2897136909    1
549            78956001    0
550          4462343293    1
551          3830053332    1
552           586671909    0
553           332888068    0
554  756937000000000000    1
555          2163813157    1
556          2602312513    1
557  813000000000000000    0
558           355883433    1
559          3229506502    1
560            20322929    0
561            16712547    0
562           268439864    0
563          2566951536    1
564           174632702    1
565           843270408    1
566          2564439320    1
567           342737458    1
568           566078011    1
569           268809577    0
570  750999000000000000    1
571            10228272    0
572           218833868    1
573           176566242    0
574          3119554528    1

[575 rows x 2 columns]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [ ]:
# ##### Importing the RandomForestClassifier and predicting whether the profile is a bot or not using it
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import accuracy_score
# from sklearn.metrics import roc_auc_score

# rfc= RandomForestClassifier(n_estimators=200,oob_score= True,n_jobs=-1,random_state=50,max_features="auto"
#                             ,min_samples_leaf=1,max_depth=15)
# rfc.fit(X_train,Y_train)
# rfc_predictions=rfc.predict(X_test)
# rfc_predictions

# test_data['bot'] = np.array(rfc_predictions)

# result = pd.DataFrame(test_data_df['id'])

# result  = result.astype(np.int64)
# result['bot'] = test_data['bot']
# result
# print (result['id'].dtype)
# print (result['bot'].dtype)
# print (result)

# result.to_csv('output_rfc_new.csv',  index=False)

# # # # #Printing the Confusion Matrix and Classification Report for RandomForestClassifier
# # # # #print
# # # # #print(confusion_matrix(Y_test,rfc_predictions))
# # # # #print('\n')
# # # # #print(classification_report(Y_test,rfc_predictions))
# # # # #print("accuracy score: {} ".format(accuracy_score(Y_test, rfc_predictions)))  
# # # # #print("AUC: {}".format(roc_auc_score(Y_test,rfc_predictions)))

In [13]:
from sklearn.cross_validation import cross_val_score
accuracyScore = cross_val_score(xgb,X_train, Y_train, cv=8, scoring='accuracy')
print("Accuracy = ",accuracyScore.mean())

('Accuracy = ', 0.92171595861423949)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
X_train,X_test,Y_train,Y_test=train_test_split(X_train,Y_train,test_size=0.15,random_state=50)
rfc= RandomForestClassifier(n_estimators=200,oob_score= True,n_jobs=-1,random_state=50,max_features="auto"
                            ,min_samples_leaf=1,max_depth=15)
rfc.fit(X_train,Y_train)
rfc_predictions=rfc.predict(X_test)
rfc_predictions
#Printing the Confusion Matrix and Classification Report for RandomForestClassifier
#print
print(confusion_matrix(Y_test,rfc_predictions))
print('\n')
print(classification_report(Y_test,rfc_predictions))
print("accuracy score: {} ".format(accuracy_score(Y_test, rfc_predictions)))  
print("AUC: {}".format(roc_auc_score(Y_test,rfc_predictions)))

[[208  15]
 [ 18 179]]


             precision    recall  f1-score   support

          0       0.92      0.93      0.93       223
          1       0.92      0.91      0.92       197

avg / total       0.92      0.92      0.92       420

accuracy score: 0.921428571429
AUC: 0.920682433817

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()
label=[]
for sentence in reviews['comments'].values:
   ## print(sentence)
    if type(sentence)==str:
        ss = sid.polarity_scores(sentence)
        if(ss['neg']>ss['pos']):
            label.append("negative")
        else:
            label.append("positive")
    else:
        label.append("NA")


reviews['sentiment_label']=label

df = pd.DataFrame(reviews)
filename = 'test_withLabel.csv'
df.to_csv(filename, index=False, encoding='utf-8')