In [1]:
#importing pandas package
import pandas as pd
import numpy as np
path_to_projectData = 'Data/' #input path where the data of the project resides
train_data_df = pd.read_csv(path_to_projectData + 'training_data_2_csv_UTF.csv') #reading the bots_data.csv file
train_data_df

#SELECTING TOP 10 ROWS FROM THE COMBINED DATASET|

,id,id_str,screen_name,location,description,url,followers_count,friends_count,listedcount,created_at,favourites_count,verified,statuses_count,lang,status,default_profile,default_profile_image,has_extended_profile,name,bot
0,8.160000e+17,"""815745789754417152""","""HoustonPokeMap""","""Houston, TX""","""Rare and strong PokŽmon in Houston, TX. See m...","""https://t.co/dnWuDbFRkt""",1291,0,10,"""Mon Jan 02 02:25:26 +0000 2017""",0,False,78554,"""en""","{\r ""created_at"": ""Sun Mar 12 15:44:04 +0...",True,False,False,"""Houston PokŽ Alert""",1
1,4.843621e+09,4843621225,kernyeahx,"Templeville town, MD, USA",From late 2014 Socium Marketplace will make sh...,NaN,1,349,0,2/1/2016 7:37,38,False,31,en,null,True,False,False,Keri Nelson,1
2,4.303727e+09,4303727112,mattlieberisbot,NaN,"Inspired by the smart, funny folks at @replyal...",https://t.co/P1e1o0m4KC,1086,0,14,Fri Nov 20 18:53:22 +0000 2015,0,False,713,en,"{'retweeted': False, 'is_quote_status': False,...",True,False,False,Matt Lieber Is Bot,1
3,3.063139e+09,3063139353,sc_papers,NaN,NaN,NaN,33,0,8,2/25/2015 20:11,0,False,676,en,Construction of human anti-tetanus single-chai...,True,True,False,single cell papers,1
4,2.955142e+09,2955142070,lucarivera16,"Dublin, United States",Inspiring cooks everywhere since 1956.,NaN,11,745,0,1/1/2015 17:44,146,False,185,en,null,False,False,False,lucarivera16,1
5,8.410000e+17,8.41E+17,dantheimprover,"Austin, TX",Just a guy trying to do good by telling everyo...,NaN,1,186,0,13/03/2017 22:53,0,False,11,en,Status(_api=<tweepy.api.API object at 0x101927...,True,False,True,dantheimprover,1
6,2.482835e+09,2482834658,_all_of_us_,in a machine.,bot by @rubicon,NaN,193,0,19,Wed May 07 22:29:25 +0000 2014,0,False,6068,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,everything always,1
7,3.333574e+09,3333573622,KatamariItems,NaN,[Bot rolled up by @BeachEpisode] Cataloguing e...,NaN,8227,2,89,Thu Jun 18 22:07:31 +0000 2015,26,False,2597,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,Katamari Collection,1
8,2.996105e+09,2996105102,AutophagyPapers,NaN,Twitterbot for #Autophagy papers. Curated by @...,NaN,275,0,17,1/25/2015 17:34,23,False,9922,en,Feeding Schedule And Proteolysis Regulate Auto...,False,False,False,Autophagy Papers,1
9,3.271096e+09,3271095818,HSC_papers,NaN,NaN,NaN,51,3,9,7/7/2015 15:23,0,False,2515,en,Functional Selectivity in Cytokine Signaling R...,True,False,False,Hematopoiesis,1
10,2.717905e+09,2717905134,everycheese,cheese land,cheese cheese cheese // updates every 4 hours ...,https://t.co/0cV8vQsQSV,51,1,12,Fri Aug 08 20:23:08 +0000 2014,0,False,111,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,all of the cheese,1
11,2.826073e+09,2826073429,gyr_papers,NaN,"Literature bot searching arXiv, biorXiv, PeerJ...",NaN,2,1,4,9/22/2014 9:46,0,False,230,en,ArXiv: Large-scale chromosome folding versus g...,True,True,False,gyrpapers,1
12,8.100000e+17,8.10E+17,lavon_court,NaN,NaN,None,0,29,0,Sun Mar 12 01:07:25 +0000 2017,0,False,0,en,None,True,True,NaN,Lavon Court,1
13,1.027584e+09,1027583707,AjstyleAlen,NaN,NaN,None,1,206,0,Sat Dec 22 02:18:49 +0000 2012,0,False,0,en,None,True,True,NaN,Alen Alex,1
14,3.949913e+08,394991274,Rupesh93505,NaN,NaN,None,0,38,0,Sun Mar 12 01:06:00 +0000 2017,0,False,0,en,None,True,True,NaN,Rajesh prajapati,1
15,3.032363e+09,3032363298,hard_to_yelp,NaN,NaN,NaN,109,0,16,Fri Feb 20 08:23:00 +0000 2015,0,False,16067,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,how hard is it to,1
16,2.568852e+09,2568851552,fuckeverywordza,NaN,Why wait until 2020 for the Z's? Fucking every...,NaN,250,0,25,Sun Jun 15 11:20:31 +0000 2014,0,False,31721,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,fuck every word z-a,1
17,2.954704e+09,2954704090,yeahTonyaGonzal,"Pensacola, USA","Musician, vegan, animal rights activist.",NaN,15,1941,1,1/1/2015 11:47,319,False,406,en,null,False,False,False,yeahTonyaGonzal,1
18,8.390000e+17,8.39E+17,BbbbggU,"_._______________, _________",_______ XXX,NaN,190,1899,0,3/7/2017 22:08,27,False,0,th,NaN,True,True,False,xXx,1
19,2.835724e+09,2835723644,ecin_gnihtaseod,NaN,"straight-up rip-off of @doesathing_nice, excep...",https://t.co/iEclQxz694,181,0,24,Tue Sep 30 04:56:09 +0000 2014,0,False,21506,en,"{u'contributors': None, u'truncated': False, u...",True,True,False,‚ƒÓ‡«äu,1
20,1.918203e+09,1918202534,tofu_product,NaN,Follow me to chat. // Reflecting your personal...,NaN,10175,11465,199,Sun Sep 29 21:35:03 +0000 2013,328,False,65022,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,tofu,1
21,2.475875e+09,2475875424,onetruewiseman,AMERICA,The Truest Wisdom (aka trying to make even les...,NaN,23,4,8,Sat May 03 19:04:37 +0000 2014,4,False,6230,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,One True Wise Man,1
22,1.909219e+09,1909219404,everycolorbot,the RGB color space,colors. all of 'em. | developed by @vogon; fe...,https://t.co/ICFGFTYbjQ,106126,0,999,Thu Sep 26 21:22:10 +0000 2013,2,False,30156,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,Every Color,1
23,4.040207e+09,4040207472,himawari8bot,Space,Unofficial; imagery courtesy: Japan Meteorolog...,https://t.co/OSHkLQWgKQ,2302,3,161,Tue Oct 27 23:06:22 +0000 2015,4,False,7640,en,"{'favorited': False, 'id_str': '84113715491497...",False,False,False,himawari8bot,1
24,3.369547e+09,3369547257,emoji__polls,‰÷•ü,A silly bot by @fourtonfish @botwikidotorg. Im...,https://t.co/OqsKPUkiXl,443,2,17,7/10/2015 18:30,6,False,9584,en,"Status(in_reply_to_user_id=None, place=None, i...",False,False,False,EMOJI POLLS!,1
25,2.555847e+09,2555847008,everytrolltroll,NaN,exposing the BLATANT HYPOCRISY of @everycanont...,NaN,27,1,10,Mon Jun 09 01:33:19 +0000 2014,0,False,145,en,"{u'contributors': None, u'truncated': False, u...",True,False,False,EveryCanonTrollTroll,1
26,2.520450e+09,2520449720,hyphizer,#botALLY,"New words, from time to time. By @derekarnold",NaN,191,2,19,Sat May 24 13:13:08 +0000 2014,0,False,5684,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,hyphizer,1
27,8.290000e+17,8.29E+17,GreenwadeGema,NaN,secr,NaN,1,35,1,Mon Feb 06 14:07:17 +0000 2017,54,False,82,en,"{""created_at"": ""Mon Mar 13 02:54:29 +0000 2017...",True,False,False,Gema Greenwade,1
28,2.886559e+09,2886558632,par_papers,NaN,"Twitterbot of #Parasitology papers in PubMed, ...",NaN,651,0,36,11/1/2014 17:27,0,False,19867,en,4-Nitro styrylquinoline is an antimalarial inh...,False,False,False,Parasitology papers,1
29,2.787206e+09,2787206222,everyMTGlegend,The Coast Where Wizards Chill,tweeting every legendary MTG card (as of 10/20...,NaN,37,45,7,Wed Sep 03 03:39:41 +0000 2014,0,False,191,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,every MTG legend,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,1.622870e+07,16228699,cesarmillan,"Los Angeles, CA",I rehabilitate dogs. I train people. I hope th...,http://t.co/DeOnYtIXOY,1017758,6985,9473,Wed Sep 10 21:36:17 +0000 2008,12901,True,13786,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Cesar Millan,0
2768,2.355272e+09,2355272027,mayauofa213,"Tucson, AZ",NaN,NaN,9,97,0,Thu Feb 20 21:40:36 +0000 2014,0,False,1,en,"{""created_at"": ""Sat Apr 12 07:16:37 +0000 2014...",True,False,True,Carlos Maya,0
2769,4.810089e+07,48100887,Andy,"ÌÏT: 40.735225,-74.006791","folo: @bravowwhl, Insta: @bravoandy, Snap: And...",https://t.co/QN7UEPy7oh,2000567,457,9674,6/17/2009 20:22,901,True,55202,en,"Status(contributors=None, truncated=False, tex...",False,False,False,Andy Cohen,0
2770,2.070461e+08,"""207046071""","""VicenteTao""","""""","""""",null,11,53,0,"""Sun Oct 24 11:36:46 +0000 2010""",1,False,13,"""en""","{\r ""created_at"": ""Tue Nov 18 07:52:08 +0...",True,False,False,"""Tang Tao""",0
2771,1.986142e+07,19861423,kar2905,"Santa Monica, California","Founder @springroleinc, Masters grad from Carn...",http://t.co/16k84nRFDc,1599,922,67,Sun Feb 01 15:03:50 +0000 2009,212,False,11240,en,{'created_at': 'Fri Mar 10 06:37:29 +0000 2017...,False,False,True,Kartik Mandaville,0
2772,1.529274e+09,1529273749,palalablo,NaN,"If I could stay in the shower all day, I would.",NaN,82,91,0,Wed Jun 19 00:48:44 +0000 2013,634,False,704,es,"{'truncated': False, 'entities': {'user_mentio...",False,False,False,Pablo,0
2773,8.002847e+08,800284734,dutt_ashish,"Bangalore, India","I'm Ashish Dutt, a Freelance Writer and Photog...",http://t.co/UELOKZ17Xb,178,325,6,Mon Sep 03 12:16:41 +0000 2012,30,False,405,en,{'created_at': 'Sun Mar 12 12:03:29 +0000 2017...,False,False,False,Ashish Dutt,0
2774,8.410000e+17,8.41E+17,KellerSeason,NaN,NaN,None,46,233,0,Thu Sep 15 18:20:41 +0000 2011,935,False,285,en,"{""created_at"": ""Fri Mar 10 00:38:52 +0000 2017...",True,False,NaN,season keller,0
2775,1.817123e+08,181712262,VitorBecker,Santos,NaN,NaN,67,168,0,8/22/2010 21:55,0,False,1851,en,"Status(contributors=None, coordinates=None, so...",False,False,False,Vitor Vaqueiro,0
2776,1.737285e+07,17372853,honorsociety,"Los Angeles, CA",https://t.co/qnAibV0nJv,NaN,147441,20889,0,Thu Nov 13 21:17:24 +0000 2008,43,True,7648,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Honor Society,0
2777,2.432640e+07,24326400,brian_littrell,Some where over the rainbow :),Husband / Father/ Backstreet Boy / Christian A...,http://t.co/QYS1k7wfP8,420699,108,5248,Sat Mar 14 04:12:42 +0000 2009,11,True,5568,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Brian Littrell,0
2778,7.477850e+07,74778498,TomJackson57,NaN,"Husband, Father, Bronco, ESPN NFL MNF Correspo...",https://t.co/OM2d9x9uh8,63866,21,2037,Wed Sep 16 17:00:34 +0000 2009,40,True,70,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Tom Jackson,0
2779,7.223549e+07,72235489,visu_bio,www.mnrindia.org,MNRF for Research n Innovation @ClubSciWri Alu...,https://t.co/JdmIKwaIV7,1715,1342,84,9/7/2009 7:57,3688,False,1395,en,"Status(contributors=None, truncated=False, tex...",False,False,True,Viswanadham Duppatla,0
2780,3.666757e+08,366675723,VivianePatty,Brasil/Rio de Janeiro,Estou a procura de amizades sinceras e bem leg...,NaN,5,67,0,9/2/2011 16:20,0,False,2,pt,null,False,False,False,Viviane Patty,0
2781,1.391862e+09,1391862175,mohsin_shk11,"Mumbai, India","Loves sports, movies and reading. Social media...",NaN,122,88,0,4/30/2013 11:35,325,False,1031,en,"Status(in_reply_to_user_id=None, lang='en', co...",False,False,True,Mohsin Shaikh,0
2782,6.161463e+07,61614633,Robbie_OC,NaN,For Booking and Contact Eileen Koch & Company ...,http://t.co/TvnoxtXtLZ,4025,487,117,Thu Jul 30 22:14:39 +0000 2009,18,True,6672,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Lewis Rocc,0
2783,8.410000e+17,8.41E+17,MiThiicSource,Canada,13 // Co-Owner Of DSYR // @YouTube Content Cre...,https://t.co/SrnbuzpdM9,52,39,0,Fri Jun 17 23:17:50 +0000 2016,689,False,206,en,"{""created_at"": ""Sat Mar 11 17:44:05 +0000 2017...",False,False,NaN,mithiicsource,0
2784,7.224801e+08,"""722480142""","""JTJ_Photo""","""Washington, DC Metro Area""","""Photographer specializing in garden and lands...","""http://t.co/dV7zMEloBp""",30,72,4,"""Sat Jul 28 16:47:30 +0000 2012""",1,False,926,"""en""","{\r ""created_at"": ""Tue Mar 07 16:19:55 +0...",False,False,False,"""Josh Taylor""",0
2785,2.190714e+07,21907142,SkillzVa,Worldwide,DJ/Host/Artist/Grammy Nominated Songwriter/Mus...,NaN,41776,1158,854,Wed Feb 25 19:36:21 +0000 2009,1264,True,1096,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Mad Skillz,0
2786,1.021249e+08,102124883,iamadityar,"New York, NY","Indian, Student of Science",NaN,52,323,2,1/5/2010 18:10,696,False,767,en,"Status(contributors=None, truncated=False, tex...",False,False,True,Aditya Ramamurthy,0
2787,6.409034e+07,64090343,haileybaldwin,East Coast,Hailey Rhode Baldwin instagramäó¢haileybaldwin...,NaN,972032,3072,1587,Sun Aug 09 02:15:48 +0000 2009,1423,True,22362,en,"{""created_at"": ""Sun Mar 12 18:30:02 +0000 2017...",False,False,False,Hailey Baldwin,0
2788,1.042267e+08,104226662,ahmadriaz,NaN,NaN,NaN,26,150,1,Tue Jan 12 17:54:43 +0000 2010,8,False,2,en,"{'retweeted': False, 'is_quote_status': False,...",True,True,False,Ahmad Riaz,0
2789,1.502883e+07,15028834,thetrickisto,"Brooklyn, NY","Tell me your successes, I want to steal them. ...",https://t.co/tc7peTn8bF,215,462,16,6/6/2008 12:13,812,False,2384,en,"Status(contributors=None, truncated=False, tex...",False,False,False,Rose Bender,0
2790,5.683425e+07,56834251,OKKenna,info@kenna.com,NaN,http://kenna.com,64219,667,698,Tue Jul 14 22:13:57 +0000 2009,2901,True,85,en,"{u'contributors': None, u'truncated': False, u...",False,False,False,Kenna,0
2791,2.191118e+09,2191117981,MixologyBot,NaN,Feeling adventurous? Try one of these!,http://t.co/HeauAEKcWi,310,0,21,11/12/2013 21:58,3,False,3909,en,"Status(contributors=None, truncated=False, tex...",True,False,False,The Mixologist,0
2792,2.362091e+08,236209129,leslieberland,NaN,"Twitter CMO. Favorite title: Mama. Never, ever...",NaN,18998,2005,425,1/10/2011 2:06,2503,False,3498,en,RT @StationCDRKelly: Dreaming of napping in sp...,False,False,True,Leslie Berland,0
2793,2.545039e+08,254503881,SamuelsPants,brooklyn NY,"I live in brooklyn, I'm a bike messenger, I pl...",http://t.co/CQkADdjfaw,32,54,0,Sat Feb 19 12:12:42 +0000 2011,1,False,97,en,"{'geo': None, 'in_reply_to_status_id': None, '...",True,False,False,Samuel Littlefield,0
2794,1.548544e+07,15485441,jimmyfallon,"New York, New York",astrophysicist,http://t.co/fgp5RYqr3T,45044433,7451,68157,7/18/2008 19:46,24,True,9606,en,"Status(contributors=None, truncated=False, tex...",False,False,False,jimmy fallon,0
2795,7.513869e+08,751386872,LocalAlligator,"England, United Kingdom","I'm quite out of my mind, actually, but people...",NaN,16,64,1,8/11/2012 14:53,15,False,62,en,{'created_at': 'Sun Feb 26 15:51:57 +0000 2017...,False,False,True,Tammas Foxdene,0
2796,1.992936e+07,19929362,RepJoeBarton,"Ennis, TX",I work for the people of the 6th District of T...,http://t.co/UcrfIiWGdl,22490,308,1342,Mon Feb 02 20:30:20 +0000 2009,43,True,1897,en,"{u'contributors': None, u'truncated': False, u...",True,False,True,Joe Barton,0

In [2]:
#import train_test_split,Imputer from sklearn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer

# selecting attributes which have numeric values and categorical values
train_data= train_data_df[['screen_name','description',
       'followers_count', 'friends_count', 'listedcount',
       'favourites_count', 'verified', 'statuses_count',
       'default_profile', 'default_profile_image', 'has_extended_profile']]


train_data['followers_count']=train_data['followers_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
train_data['friends_count']=train_data['friends_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
train_data['listedcount']=train_data['listedcount'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
train_data['favourites_count']=train_data['favourites_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)

#y = lambda symbol: 'X' if symbol==True else 'O' if symbol==False else ' '

train_data['verified']=train_data['verified'].apply(lambda x: 0 if x==False else 1 if x==True else -1)
train_data['default_profile']=train_data['default_profile'].apply(lambda x: 0 if x==False else 1 if x==True else -1)
train_data['default_profile_image']=train_data['default_profile_image'].apply(lambda x: 0 if x==False else 1 if x==True else -1)
train_data['has_extended_profile']=train_data['has_extended_profile'].apply(lambda x: 0 if x==False else 1 if x==True else -1)




train_data['is_bot_screenname']=0
train_data['is_bot_screenname'] = train_data['screen_name'].apply(lambda x:1 if 'bot' in x  else 1 if 'Bot' in x  else 1 
                                                                   if 'BOT' in x else 0)
train_data.drop('screen_name', axis=1, inplace=True)

train_data['is_bot_description']=0

#Looking for the word bot in description            
description = train_data['description']
flag = []
for x in description:
    x = str(x)
    if 'bot' in x or 'BOT' in x or 'Bot' in x:
        flag.append(1)
    else:
        flag.append(0)
train_data['is_bot_description']=flag
train_data.drop('description', axis=1, inplace=True)

# #namelength
# train_data['name_len']=0

# profilenames = train_data['name']
# namelen = []
# for i in profilenames:
#     namelen.append(len(i))
# train_data['name_len']=namelen


# train_data.drop('name', axis=1, inplace=True)


# train_data['url']=train_data['url'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)
train_data


# train_data

# df = pd.DataFrame(['05/06/2015 00:00', '22/06/2015 00:00', None], columns=['myDate'])
# df['diff']= pd.to_datetime(train_data['myDate'], coerce=True) - pd.datetime.now().date()
# df

X_train = train_data
Y_train= train_data_df['bot']

print(X_train)

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      followers_count  friends_count  listedcount  favourites_count  verified  \
0                1291              0           10                 0         0
1                   1            349            0                38         0
2                1086              0           14                 0         0
3                  33              0            8                 0         0
4                  11            745            0               146         0
5                   1            186            0                 0         0
6                 193              0           19                 0         0
7                8227              2           89                26         0
8                 275              0           17                23         0
9                  51              3            9                 0         0
10                 51              1           12                 0         0
11                  2              1            4                 0         0
12                  0             29            0                 0         0
13                  1            206            0                 0         0
14                  0             38            0                 0         0
15                109              0           16                 0         0
16                250              0           25                 0         0
17                 15           1941            1               319         0
18                190           1899            0                27         0
19                181              0           24                 0         0
20              10175          11465          199               328         0
21                 23              4            8                 4         0
22             106126              0          999                 2         0
23               2302              3          161                 4         0
24                443              2           17                 6         0
25                 27              1           10                 0         0
26                191              2           19                 0         0
27                  1             35            1                54         0
28                651              0           36                 0         0
29                 37             45            7                 0         0
...               ...            ...          ...               ...       ...
2767          1017758           6985         9473             12901         1
2768                9             97            0                 0         0
2769          2000567            457         9674               901         1
2770               11             53            0                 1         0
2771             1599            922           67               212         0
2772               82             91            0               634         0
2773              178            325            6                30         0
2774               46            233            0               935         0
2775               67            168            0                 0         0
2776           147441          20889            0                43         1
2777           420699            108         5248                11         1
2778            63866             21         2037                40         1
2779             1715           1342           84              3688         0
2780                5             67            0                 0         0
2781              122             88            0               325         0
2782             4025            487          117                18         1
2783               52             39            0               689         0
2784               30             72            4                 1         0
2785            41776           1158          854              1264         1
2786               52            323            2               696         0
2787           972032           3072         1587              1423         1
2788               26            150            1                 8         0
2789              215            462           16               812         0
2790            64219            667          698              2901         1
2791              310              0           21                 3         0
2792            18998           2005          425              2503         0
2793               32             54            0                 1         0
2794         45044433           7451        68157                24         1
2795               16             64            1                15         0
2796            22490            308         1342                43         1

      statuses_count  default_profile  default_profile_image  \
0              78554                1                      0
1                 31                1                      0
2                713                1                      0
3                676                1                      1
4                185                0                      0
5                 11                1                      0
6               6068                0                      0
7               2597                1                      0
8               9922                0                      0
9               2515                1                      0
10               111                0                      0
11               230                1                      1
12                 0                1                      1
13                 0                1                      1
14                 0                1                      1
15             16067                1                      0
16             31721                1                      0
17               406                0                      0
18                 0                1                      1
19             21506                1                      1
20             65022                1                      0
21              6230                0                      0
22             30156                1                      0
23              7640                0                      0
24              9584                0                      0
25               145                1                      0
26              5684                0                      0
27                82                1                      0
28             19867                0                      0
29               191                0                      0
...              ...              ...                    ...
2767           13786                0                      0
2768               1                1                      0
2769           55202                0                      0
2770              13                1                      0
2771           11240                0                      0
2772             704                0                      0
2773             405                0                      0
2774             285                1                      0
2775            1851                0                      0
2776            7648                0                      0
2777            5568                0                      0
2778              70                0                      0
2779            1395                0                      0
2780               2                0                      0
2781            1031                0                      0
2782            6672                0                      0
2783             206                0                      0
2784             926                0                      0
2785            1096                0                      0
2786             767                0                      0
2787           22362                0                      0
2788               2                1                      1
2789            2384                0                      0
2790              85                0                      0
2791            3909                1                      0
2792            3498                0                      0
2793              97                1                      0
2794            9606                0                      0
2795              62                0                      0
2796            1897                1                      0

      has_extended_profile  is_bot_screenname  is_bot_description
0                        0                  0                   0
1                        0                  0                   0
2                        0                  1                   1
3                        0                  0                   0
4                        0                  0                   0
5                        1                  0                   0
6                        0                  0                   1
7                        0                  0                   1
8                        0                  0                   1
9                        0                  0                   0
10                       0                  0                   0
11                       0                  0                   1
12                      -1                  0                   0
13                      -1                  0                   0
14                      -1                  0                   0
15                       0                  0                   0
16                       0                  0                   0
17                       0                  0                   0
18                       0                  0                   0
19                       0                  0                   1
20                       0                  0                   0
21                       0                  0                   0
22                       0                  1                   0
23                       0                  1                   1
24                       0                  0                   1
25                       0                  0                   0
26                       0                  0                   0
27                       0                  0                   0
28                       0                  0                   1
29                       0                  0                   0
...                    ...                ...                 ...
2767                     0                  0                   0
2768                     1                  0                   0
2769                     0                  0                   0
2770                     0                  0                   0
2771                     1                  0                   0
2772                     0                  0                   0
2773                     0                  0                   0
2774                    -1                  0                   0
2775                     0                  0                   0
2776                     0                  0                   0
2777                     0                  0                   0
2778                     0                  0                   0
2779                     1                  0                   0
2780                     0                  0                   0
2781                     1                  0                   0
2782                     0                  0                   0
2783                    -1                  0                   0
2784                     0                  0                   0
2785                     0                  0                   0
2786                     1                  0                   0
2787                     0                  0                   0
2788                     0                  0                   0
2789                     0                  0                   0
2790                     0                  0                   0
2791                     0                  1                   0
2792                     1                  0                   0
2793                     0                  0                   0
2794                     0                  0                   0
2795                     1                  0                   0
2796                     1                  0                   0

[2797 rows x 11 columns]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [3]:
test_data_df= pd.read_csv(path_to_projectData + 'test_data_4_students.csv')
##test_data_df.replace('None',0,inplace=True)
test_data_df.head(10)

test_data_df=test_data_df.head(575)
ttest_data_df=test_data_df.head(575)
test_data=test_data_df[['screen_name','description',
       'followers_count', 'friends_count', 'listed_count',
       'favorites_count', 'verified', 'statuses_count',
       'default_profile', 'default_profile_image', 'has_extended_profile']]


#df.Age.apply(lambda x: x if not pd.isnull(x) else 'Is Null value')
test_data['followers_count']=test_data['followers_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data['friends_count']=test_data['friends_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data['listed_count']=test_data['listed_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)
test_data['favorites_count']=test_data['favorites_count'].apply(lambda x: 0 if x=='None' else 0 if x=='NaN' else x)

#y = lambda symbol: 'X' if symbol==True else 'O' if symbol==False else ' '

test_data['verified']=test_data['verified'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)
test_data['default_profile']=test_data['default_profile'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)
test_data['default_profile_image']=test_data['default_profile_image'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)
test_data['has_extended_profile']=test_data['has_extended_profile'].apply(lambda x: 0 if x=='FALSE' else 1 if x=='TRUE' else -1)

#test_data['is_bot_description']=0

test_data['is_bot_screenname']=0
test_data['is_bot_screenname'] = test_data['screen_name'].apply(lambda x:1 if 'bot' in x  else 1 if 'Bot' in x  else 1 
                                                                   if 'BOT' in x else 0)
test_data.drop('screen_name', axis=1, inplace=True)


test_data['followers_count'].fillna(0,inplace=True)
test_data['friends_count'].fillna(0,inplace=True)
test_data['listed_count'].fillna(0,inplace=True)
test_data['favorites_count'].fillna(0,inplace=True)
test_data['verified'].fillna(-1,inplace=True)
test_data['default_profile'].fillna(-1,inplace=True)
test_data['default_profile_image'].fillna(-1,inplace=True)
test_data['has_extended_profile'].fillna(-1,inplace=True)
test_data['statuses_count'].fillna(0,inplace=True)


test_data['is_bot_description']=0

#Looking for the word bot in description            
description = test_data['description']
flag = []
for x in description:
    x = str(x)
    if 'bot' in x or 'BOT' in x or 'Bot' in x:
        flag.append(1)
    else:
        flag.append(0)
test_data['is_bot_description']=flag
test_data.drop('description', axis=1, inplace=True)

#Length of name
# test_data['name_len']=0

# profilenames = test_data['name']
# namelen = []
# for i in profilenames:
#     namelen.append(len(i))
# test_data['name_len']=namelen


# test_data.drop('name', axis=1, inplace=True)

# test_data['url']=test_data['url'].apply(lambda x: 0 if x=='None' else -1 if x=='NaN' else 1)



X_test=test_data

print(X_test)
#test_data['followers_count'].fillna(0,inplace=True)
#test_data['followers_count'] = test_data['followers_count'].astype(np.int64)

#test_data.apply(pd.to_numeric,errors='coerce')

#Y_train=Imputer().fit_transform(test_data)

##print(type(test_data['followers_count']))

##dtypeCount = [test_data.iloc[:,i].apply(type).value_counts() for i in range(test_data.shape[1])]
##dtypeCount

##print(type(train_data['verified']))

##print(pd.get_dummies(test_data.verified))
#test_data.fillna(value=np.nan, inplace=True)

##df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=['A', 'B', 'C', 'D'])

##test_data=pd.DataFrame(np.random.randn(8, 4),index=test_data_df,columns=['followers_count','friends_count','listedcount','favourites_count'])

##test_data= test_data_df.ix[:,['followers_count','friends_count','listedcount','favourites_count','verified','statuses_count',
  ##            'default_profile','default_profile_image','has_extended_profile']]




##Y_train= test_data # filling the NaN and infinite values

##Y_train.head(10)
##test_data.head(10)

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

    followers_count friends_count listed_count favorites_count  verified  \
0              4466          1295          111            1579         1
1               295          1016           10             300         0
2           1001678          3017           14           13040         1
3               445           487           17            1112         0
4               187            68           13               0        -1
5                80            87            0               0        -1
6              2020          1978           56               0        -1
7                70            80            2               0        -1
8               181           144            2               0        -1
9          20419393             9            6               0         1
10            20423             8          130               0         0
11             1436          2017           55            1099         1
12         26376073            91        60767               0         1
13         27950120           157        32993               0         1
14             5210          2555          232            1169         1
15         16328463          1071        10848               0         1
16              964           331           15            2832         0
17             5254          2407          102            3082         0
18              446           431            4               0        -1
19             1404             0            2              12         0
20         16933838            21        14682               0         1
21             8619          3229          190           50921         1
22         15610695            36        15248               0         1
23         15836207          1046        32067               0         1
24            14749          1843          584            2389         1
25              191           228            5             164         0
26         25557131           672        51993               0         1
27            13206           964          496            3426         1
28             1641           812           91            1493         0
29          4545529          2042        12664           13260         1
..              ...           ...          ...             ...       ...
545             371             4            0               3         0
546             263           397            1               0        -1
547              50             1            0               1         0
548             549            21          298               6         0
549            4067           360          152            3402         1
550             486           116           12               0        -1
551             331           375           18              49         0
552        16779295             0         9213               0         1
553             892           355           16             500         0
554              25             4            2               0         0
555             993            47         1047              13         0
556             210           200           13            1442         0
557             231           127            1              64         0
558             980           107           59               4         0
559              19             7            1              20         0
560        29145797           800        27906               0         1
561             297           191           12              32         0
562        16296072            23        20704               0         1
563              15             0            0               0        -1
564            3065          3517           94               0        -1
565             120            71            3               0        -1
566             113           226            3               0        -1
567              66            84            5               0        -1
568              47            16            3               0        -1
569           26841          3359          491          130876         0
570            1551           138         3119               1         0
571        67697733           998        82023               0         1
572            1257           363           75               0        -1
573        21585872          2279       128136               0         1
574              64            80            3               0         0

     statuses_count  default_profile  default_profile_image  \
0            3036.0                0                      0
1             618.0                0                      0
2            3329.0                1                      0
3              46.0                0                      0
4          690359.0               -1                     -1
5           20167.0                1                     -1
6          968182.0                1                     -1
7           76735.0                1                     -1
8            1960.0                1                     -1
9             468.0               -1                     -1
10          17387.0                0                      0
11            967.0                0                      0
12           2666.0               -1                     -1
13            287.0               -1                     -1
14           5501.0                0                      0
15          14596.0               -1                     -1
16           6389.0                0                      0
17           3392.0                1                      0
18         119680.0               -1                     -1
19            141.0                1                      0
20           3673.0               -1                     -1
21          38918.0                0                      0
22          82958.0               -1                     -1
23          27660.0               -1                     -1
24          20076.0                0                      0
25             24.0                0                      0
26           7051.0               -1                     -1
27          14115.0                0                      0
28           3385.0                0                      0
29           9370.0                0                      0
..              ...              ...                    ...
545          1892.0                0                      0
546         62000.0                1                     -1
547          4200.0                1                      0
548        245021.0                1                      0
549          4061.0                0                      0
550        306390.0               -1                     -1
551          4313.0                0                      0
552          3698.0               -1                     -1
553          1028.0                1                      0
554          1323.0                1                      0
555         18369.0                1                      0
556         68691.0                1                      0
557            87.0                1                      0
558         14979.0                1                      0
559         26181.0                1                      0
560         42988.0               -1                     -1
561           296.0                0                      0
562           973.0               -1                     -1
563         70833.0                1                     -1
564         74560.0               -1                     -1
565         51891.0                1                      1
566         24115.0                1                     -1
567        234290.0                1                      1
568        178704.0                1                     -1
569         90417.0                0                      0
570         37318.0                1                      0
571         19364.0               -1                     -1
572        388672.0                1                     -1
573          3318.0               -1                     -1
574         43438.0                1                      0

     has_extended_profile  is_bot_screenname  is_bot_description
0                       0                  0                   0
1                       0                  0                   0
2                       1                  0                   0
3                       1                  0                   0
4                      -1                  1                   1
5                      -1                  1                   1
6                      -1                  1                   1
7                      -1                  1                   1
8                      -1                  1                   1
9                      -1                  0                   0
10                      0                  1                   1
11                      1                  0                   0
12                     -1                  0                   0
13                     -1                  0                   0
14                      0                  0                   0
15                     -1                  0                   0
16                      1                  0                   0
17                      1                  0                   0
18                     -1                  1                   1
19                      0                  1                   1
20                     -1                  0                   0
21                      1                  0                   0
22                     -1                  0                   0
23                     -1                  0                   0
24                      0                  0                   0
25                      1                  0                   0
26                     -1                  0                   0
27                      0                  0                   0
28                      0                  0                   0
29                      0                  0                   0
..                    ...                ...                 ...
545                     0                  1                   0
546                    -1                  0                   1
547                     0                  0                   1
548                     0                  0                   1
549                     0                  0                   0
550                    -1                  1                   1
551                     0                  0                   1
552                    -1                  0                   0
553                     0                  0                   0
554                     0                  0                   1
555                     0                  1                   0
556                     0                  1                   1
557                     0                  0                   0
558                     0                  0                   1
559                     0                  1                   1
560                    -1                  0                   0
561                     0                  0                   0
562                    -1                  0                   0
563                    -1                  1                   1
564                    -1                  1                   1
565                    -1                  1                   1
566                    -1                  1                   1
567                    -1                  1                   0
568                    -1                  1                   1
569                     0                  0                   0
570                     1                  1                   1
571                    -1                  0                   0
572                    -1                  1                   1
573                    -1                  0                   0
574                     0                  1                   1

[575 rows x 11 columns]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [4]:
#Importing the DecisionTreeClassifier and predicting whether the profile is a bot or not using it
from sklearn.tree import DecisionTreeClassifier
dtree= DecisionTreeClassifier()
dtree.fit(X_train,Y_train)
dtree_predictions=dtree.predict(X_test)

#Importing the classification_report,confusion_matrix from sklearn.metrics package
from sklearn.metrics import classification_report,confusion_matrix

#Printing the Confusion Matrix and Classification Report for DecisionTreeClassifier
#print(confusion_matrix(Y_test,dtree_predictions))
#print('\n')
#print(classification_report(Y_test,dtree_predictions))

#print("accuracy score: {} ".format(accuracy_score(Y_test, dtree_predictions)))  
#print("AUC: {}".format(roc_auc_score(Y_test,dtree_predictions)))

In [5]:
##### Importing the RandomForestClassifier and predicting whether the profile is a bot or not using it
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

rfc= RandomForestClassifier(n_estimators=200,oob_score= True,n_jobs=-1,random_state=50,max_features="auto"
                            ,min_samples_leaf=1,max_depth=10)
rfc.fit(X_train,Y_train)
rfc_predictions=rfc.predict(X_test)
rfc_predictions

test_data['bot'] = np.array(rfc_predictions)

result = pd.DataFrame(test_data_df['id'])

result  = result.astype(np.int64)
result['bot'] = test_data['bot']
result
print (result['id'].dtype)
print (result['bot'].dtype)
print (result)

result.to_csv('output_newdoc_3.csv',  index=False)

#Printing the Confusion Matrix and Classification Report for RandomForestClassifier
#print
#print(confusion_matrix(Y_test,rfc_predictions))
#print('\n')
#print(classification_report(Y_test,rfc_predictions))
#print("accuracy score: {} ".format(accuracy_score(Y_test, rfc_predictions)))  
#print("AUC: {}".format(roc_auc_score(Y_test,rfc_predictions)))

int64
int64
                     id  bot
0            2281292622    0
1            2344040251    0
2             765871267    0
3            4772373433    0
4            1324548560    1
5            2561341789    1
6             347810134    1
7             856303860    1
8    832875000000000000    1
9              88856792    0
10   713557000000000000    1
11           1566746503    0
12             90420314    0
13            184910040    0
14            157690631    0
15             42420346    0
16             42382447    0
17             43993280    0
18           2305236733    1
19   742794000000000000    1
20             31348594    0
21            122085859    0
22             23573083    0
23             43152482    0
24            188857501    0
25           2911272579    0
26             35094637    0
27            146252766    0
28             85430866    0
29             55117855    0
..                  ...  ...
545  731201000000000000    1
546           612754791    1
547          4493562022    1
548          2897136909    1
549            78956001    0
550          4462343293    1
551          3830053332    1
552           586671909    0
553           332888068    0
554  756937000000000000    1
555          2163813157    1
556          2602312513    1
557  813000000000000000    0
558           355883433    1
559          3229506502    1
560            20322929    0
561            16712547    0
562           268439864    0
563          2566951536    1
564           174632702    1
565           843270408    1
566          2564439320    1
567           342737458    1
568           566078011    1
569           268809577    0
570  750999000000000000    1
571            10228272    0
572           218833868    1
573           176566242    0
574          3119554528    1

[575 rows x 2 columns]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [6]:
from sklearn.cross_validation import cross_val_score
accuracyScore = cross_val_score(rfc,X_train, Y_train, cv=5, scoring='accuracy')
print("Accuracy = ",accuracyScore.mean())

/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

('Accuracy = ', 0.90417954138884371)

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
X_train,X_test,Y_train,Y_test=train_test_split(X_train,Y_train,test_size=0.15,random_state=50)
rfc= RandomForestClassifier(n_estimators=200,oob_score= True,n_jobs=-1,random_state=50,max_features="auto"
                            ,min_samples_leaf=1,max_depth=15)
rfc.fit(X_train,Y_train)
rfc_predictions=rfc.predict(X_test)
rfc_predictions
#Printing the Confusion Matrix and Classification Report for RandomForestClassifier
#print
print(confusion_matrix(Y_test,rfc_predictions))
print('\n')
print(classification_report(Y_test,rfc_predictions))
print("accuracy score: {} ".format(accuracy_score(Y_test, rfc_predictions)))  
print("AUC: {}".format(roc_auc_score(Y_test,rfc_predictions)))

[[210  13]
 [ 24 173]]


             precision    recall  f1-score   support

          0       0.90      0.94      0.92       223
          1       0.93      0.88      0.90       197

avg / total       0.91      0.91      0.91       420

accuracy score: 0.911904761905
AUC: 0.909938312353

In [8]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()
label=[]
for sentence in reviews['comments'].values:
   ## print(sentence)
    if type(sentence)==str:
        ss = sid.polarity_scores(sentence)
        if(ss['neg']>ss['pos']):
            label.append("negative")
        else:
            label.append("positive")
    else:
        label.append("NA")


reviews['sentiment_label']=label

df = pd.DataFrame(reviews)
filename = 'test_withLabel.csv'
df.to_csv(filename, index=False, encoding='utf-8')

/anaconda/lib/python2.7/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

LookupError:
**********************************************************************
  Resource
  u'sentiment/vader_lexicon.zip/vader_lexicon/vader_lexicon.txt'
  not found.  Please use the NLTK Downloader to obtain the
  resource:  >>> nltk.download()
  Searched in:
    - '/Users/Fiona/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************